CHANGE docs to 3.0.0 && Lint js && UPDATE to use 3.0.0-alpha && FIX webpack
storybooks/storybooks.github.io pull request #54
Opened 2017-05-21 08:09 UTC by ndelangen

Issue: https://github.com/storybooks/storybook/issues/1046

## What I did
- updated all the package references to the new package names
- removed the use of links and actions from `@storybook/react`.
- UPDATED to the latest alpha of storybook
- FIX the webpack config

2017-05-21 08:11 UTC, ndelangen commented
@shilman @UsulPro please review?

please pay attention to the package `gh-pages` being updated, I'm not sure if this will impact anything.

2017-05-21 09:42 UTC, shilman requested changes
@ndelangen 

I'm getting an error when I try to run:
```
unknown color: rgb(NaN,NaN,NaN)
```

Also it looks like a lot of the CSS has been removed? Does it look OK on your machine when you `yarn develop`?

2017-05-21 09:42 UTC, shilman commented on stories/data.js
> +import { linkTo } from @storybook/react
`import { linkTo } from '@storybook/addon-links';`

2017-05-22 01:40 UTC, shilman commented
@ndelangen thanks for improving the docs!

two comments:

1) i'm still getting the `unknown color: rgb(NaN,NaN,NaN)` error when i run `yarn develop` -- gatsby is broken

2) let's do the storybook improvements (e.g. adding knobs) in a separate PR, so we can discuss it independently!

2017-05-22 12:39 UTC, ndelangen commented
OK, I will continue working on it.

2017-05-22 18:36 UTC, ndelangen commented
Should all be fixed now, please check?

2017-05-23 05:30 UTC, shilman requested changes
Minor changes needed, although these are not really related to your change

2017-05-23 05:30 UTC, shilman commented on components/Homepage/Platforms/index.js
> +          href="https://github.com/storybooks/storybook/tree/master/packages/react-storybook"
https://github.com/storybooks/storybook/tree/master/app/react

2017-05-23 05:30 UTC, shilman commented on components/Homepage/Platforms/index.js
> +          href="https://github.com/storybooks/storybook/tree/master/packages/react-native-storybook"
https://github.com/storybooks/storybook/tree/master/app/react-native

2017-05-23 05:33 UTC, shilman commented
@ndelangen fixed these separately here: https://github.com/storybooks/storybooks.github.io/pull/58

2017-05-23 10:40 UTC, shilman approved these changes

2017-05-28 19:02 UTC, closed without merging